#-  Ruby dependency management file

#-  Gemfile ~~
#                                                       ~~ (c) SRW, 25 Apr 2013
#                                                   ~~ last updated 04 Feb 2015

from_dir = {
    path: File.join(Dir.pwd, '..', '..', 'src', 'ruby-gem')
}

from_git = {
    git: 'https://github.com/qmachine/qm-ruby.git'
}

gem 'facter'
gem 'json'
gem 'qm', (FileTest.directory?(from_dir[:path]) ? from_dir : from_git)

platforms 'ruby' do
  # This only runs on platforms that allow native C extensions by default.
    gem 'hiredis'
    gem 'sqlite3'
end

ruby '2.2.0'

source 'https://rubygems.org'

#-  vim:set syntax=ruby:
