#-  Ruby dependency management file

#-  Gemfile ~~
#                                                       ~~ (c) SRW, 25 Apr 2013
#                                                   ~~ last updated 14 Nov 2014

source 'https://rubygems.org'

ruby '2.1.5'

gem 'json'
gem 'qm', :git => 'https://github.com/qmachine/qm-ruby.git'
gem 'thin'

#-  vim:set syntax=ruby:
