#-  Ruby dependency management file

#-  Gemfile ~~
#
#   This app runs just fine on Heroku now, but it only supports MongoDB for
#   storage.
#
#                                                       ~~ (c) SRW, 25 Apr 2013
#                                                   ~~ last updated 31 Jul 2014

source 'https://rubygems.org'

gem 'json'
gem 'qm', :git => 'https://github.com/qmachine/qm-ruby.git'
gem 'thin'

#-  vim:set syntax=ruby:
