#-  GNU Makefile

#-  Makefile ~~
#
#   This contains live instructions for submitting QMachine to Microsoft's
#   Internet Explorer Gallery (http://www.iegallery.com/) as a Pinned Site.
#
#                                                       ~~ (c) SRW, 27 Jun 2012

include $(PWD)/../../tools/macros.make

.PHONY: all
.SILENT: ;

all:
	@   $(call aside, '(ie9-gallery placeholder)')

###

%:
	@   $(call alert, 'No target "$@" found.')

#-  vim:set syntax=make:
