#-  GNU Makefile

#-  Makefile ~~
#                                                       ~~ (c) SRW, 22 Mar 2012

include $(PWD)/../../tools/macros.make

.PHONY: all
.SILENT: ;

all:
	@   $(call aside, '(facebook-app placeholder)')

###

%:
	@   $(call alert, 'No target "$@" found.')

#-  vim:set syntax=make:
